package com.smartnotes.servlet;

import com.smartnotes.dao.NoteDAO;
import com.smartnotes.model.Note;
import com.smartnotes.util.GeminiAPIClient;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;

@WebServlet("/api/flashcards")
public class AIFlashcardServlet extends HttpServlet {

    private NoteDAO noteDAO;
    private GeminiAPIClient geminiAPIClient;

    @Override
    public void init() throws ServletException {
        noteDAO = new NoteDAO();
        geminiAPIClient = new GeminiAPIClient();
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        response.setContentType("application/json");
        response.setCharacterEncoding("UTF-8");

        String noteIdStr = request.getParameter("noteId");
        
        if (noteIdStr == null || noteIdStr.trim().isEmpty()) {
            sendError(response, "Note ID is required");
            return;
        }

        try {
            int noteId = Integer.parseInt(noteIdStr);
            Note note = noteDAO.getNoteById(noteId);

            if (note == null) {
                sendError(response, "Note not found");
                return;
            }

            // Call the AI client to generate flashcards
            String flashcardsJson = geminiAPIClient.generateFlashcards(note.getContent());

            if (flashcardsJson.startsWith("Error:")) {
                sendError(response, flashcardsJson);
            } else {
                try (PrintWriter out = response.getWriter()) {
                    // Send back the raw JSON generated by the AI
                    out.print(flashcardsJson);
                    out.flush();
                }
            }
        } catch (NumberFormatException e) {
            sendError(response, "Invalid Note ID");
        } catch (Exception e) {
            sendError(response, "Error generating flashcards: " + e.getMessage());
        }
    }

    private void sendError(HttpServletResponse response, String message) throws IOException {
        response.setStatus(HttpServletResponse.SC_BAD_REQUEST);
        try (PrintWriter out = response.getWriter()) {
            out.print("{\"error\": \"" + message.replace("\"", "\\\"") + "\"}");
            out.flush();
        }
    }
}
